#!/bin/bash

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

$SHEEP $STORE/0 -z 0 -p 7000 -c $DRIVER
sleep 1

# start Sheepdog with one node
$COLLIE cluster format
sleep 1

# launch sheeps simultaneously
for i in `seq 1 9`; do
    $SHEEP $STORE/$i -z $i -p 700$i -c $DRIVER
done

sleep 1

echo check whether all nodes have the same cluster info
for i in `seq 0 9`; do
    $COLLIE cluster info -p 700$i | _filter_cluster_info > /tmp/cinfo.$i
done
for i in `seq 1 9`; do
    diff -u /tmp/cinfo.0 /tmp/cinfo.$i
done
