#!/bin/bash

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in `seq 0 7`; do
    $SHEEP $STORE/$i -z $i -p 700$i -c $DRIVER
done

while true; do
    sleep 2
    if [ $($COLLIE node list | wc -l) -eq 9 ]; then
	break
    fi
done

$COLLIE cluster format -c 3
sleep 1

for i in `seq 0 4`; do
    $COLLIE vdi create test$i 100M
done

for i in `seq 0 4`; do
    dd if=/dev/urandom | $COLLIE vdi write test$i -p 7000 &
done

sleep 3

echo begin kill
for i in `seq 1 5`; do
    pkill -f "$SHEEP $STORE/$i -z $i -p 700$i"
    sleep 3
done

for i in `seq 1 5`; do
    $SHEEP $STORE/$i -z $i -p 700$i -c $DRIVER
done

echo wait for object recovery to finish
while true; do
    if [ "$(pgrep collie)" ]; then
        sleep 1
    else
        break
    fi
done

for i in `seq 0 4`; do
    for port in `seq 0 7`; do
        $COLLIE vdi read test$i -p 700$port | md5sum > /tmp/csum.$port
    done
    for port in `seq 1 7`; do
        diff -u /tmp/csum.0 /tmp/csum.$port
    done
done
