#!/bin/bash

# Test doing heavy IO while confchg change

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in `seq 0 7`; do
    _start_sheep $i
done

_wait_for_sheep "8"

$COLLIE cluster format -c 3
sleep 1

for i in `seq 0 4`; do
    $COLLIE vdi create test$i 100M
done

for i in `seq 0 4`; do
    dd if=/dev/urandom | $COLLIE vdi write test$i -p 7000 &
done

sleep 3

echo begin kill
for i in `seq 1 5`; do
    _kill_sheep $i
    sleep 3
done

for i in `seq 1 5`; do
    _start_sheep $i
done

echo wait for object recovery to finish
_wait_for_collie

for i in `seq 0 4`; do
    for port in `seq 0 7`; do
        $COLLIE vdi read test$i -p 700$port | md5sum > /tmp/csum.$port
    done
    for port in `seq 1 7`; do
        diff -u /tmp/csum.0 /tmp/csum.$port
    done
done
