#!/bin/bash

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

_start_sheep 0
_start_sheep 1

sleep 2

$COLLIE cluster format -c 2
$COLLIE cluster recover disable

qemu-img create sheepdog:test 4G

# create 20 objects
for i in `seq 0 19`; do
    $COLLIE vdi write test $((i * 4 * 1024 * 1024)) 512 < /dev/zero
done

_start_sheep 2

# overwrite the objects
for i in `seq 0 19`; do
    $COLLIE vdi write test $((i * 4 * 1024 * 1024)) 512 < /dev/zero
done
