#!/bin/bash

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

$SHEEP $STORE/0 -z 0 -p 7000 -c $DRIVER
$SHEEP $STORE/1 -z 1 -p 7001 -c $DRIVER

sleep 2

$COLLIE cluster format -c 2
$COLLIE cluster recover disable

qemu-img create sheepdog:test 4G

# create 20 objects
for i in `seq 0 19`; do
    $COLLIE vdi write test $((i * 4 * 1024 * 1024)) 512 < /dev/zero
done

$SHEEP $STORE/2 -z 2 -p 7002 -c $DRIVER

# overwrite the objects
for i in `seq 0 19`; do
    $COLLIE vdi write test $((i * 4 * 1024 * 1024)) 512 < /dev/zero
done
