#!/bin/bash

# Test sheep booting on existing images mounted as loop device

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

_make_device 0 $((2 * 1024 ** 3))
_make_device 1 $((4 * 1024 ** 3))
_make_device 2 $((8 * 1024 ** 3))

for i in 0 1 2; do
    _start_sheep $i
done

_wait_for_sheep 3

echo check the number of vnodes
for i in 0 1 2; do
    $COLLIE node list -p 700$i
done

status=0
