#!/bin/bash

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 1 2; do
    $SHEEP $STORE/$i/ -z $i -p 700$i -c $DRIVER
done

# add gateway node
$SHEEP $STORE/4/ -z 4 -p 7004 -c $DRIVER -g

sleep 1

echo check the number of vnodes
$COLLIE node list
