#!/bin/bash

# Test gateway only functionality

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 1 2; do
    _start_sheep $i
done

_wait_for_sheep 3

# add gateway node
_start_sheep 4 "-g"

_wait_for_sheep 4

echo check the number of vnodes
$COLLIE node list
