#!/bin/bash

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 1 2; do
    _start_sheep $i
done

sleep 1

$COLLIE cluster format -c 1

qemu-img create sheepdog:test 4G
for i in `seq 1 9`; do
    qemu-io -c "write 0 512 -P $i" sheepdog:test | _filter_qemu_io
    qemu-img snapshot -c tag$i sheepdog:test
done

qemu-io -c "read 0 512 -P 9" sheepdog:test | _filter_qemu_io
for i in `seq 1 9`; do
    qemu-io -c "read 0 512 -P $i" sheepdog:test:tag$i | _filter_qemu_io
done
