#!/bin/bash

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 2; do
    $SHEEP $STORE/$i -z $i -p 700$i -c $DRIVER
done

sleep 1

$COLLIE cluster format -c 2
$COLLIE vdi create test 539545600
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
_wait_for_collie
echo "there should be 3 setattr errors"

$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
_wait_for_collie
echo "there should be 8 setattr errors"

$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
_wait_for_collie
echo "there should be 6 setattr errors"

$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
$COLLIE vdi setattr test lock 1 -x &
_wait_for_collie
echo "there should be 5 setattr errors"
