#!/bin/bash

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 1 2; do
    $SHEEP $STORE/$i -s 4096 -p 700$i -z $i -c $DRIVER
done

sleep 1;

$COLLIE cluster format -c 3
$COLLIE vdi create base 100M -P

qemu-img snapshot -c tag sheepdog:base

sleep 1

$COLLIE vdi clone -s 1 base test

sleep 1

$COLLIE vdi delete test

sleep 1
$COLLIE vdi delete base

sleep 1
$COLLIE vdi delete -s 1 base

sleep 3
echo there should be no vdi
$COLLIE vdi list

echo there should be no object
$COLLIE node info
