#!/bin/bash

# Test sockfd keepalive

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

trap "_uninit; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_uninit()
{
	for i in `seq 1 4`; do
		_cleanup_machine_simulation $i
	done
}

_cleanup

for i in `seq 0 5`; do
	_start_sheep $i
done

_wait_for_sheep 6

$COLLIE cluster format -c 3 -m unsafe

$COLLIE vdi create test 40M
dd if=/dev/urandom | $COLLIE vdi write test &

sleep 3
for i in `seq 1 4`; do
	_simulate_machine_down $i
done

_wait_for_collie

for i in `seq 0 9`; do
	$COLLIE vdi object -i $i test
done

status=0
