#!/bin/bash

# Test md disk failure with node change events
seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!
md=true

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 1 2; do
	_start_sheep $i
done
_wait_for_sheep 3
$COLLIE cluster format
sleep 1
$COLLIE vdi create test 200M -P

# node event after disk failure
_safe_remove $STORE/0/d0

_random | $COLLIE vdi write test &
sleep 1
_start_sheep 3
_wait_for_sheep 4
_wait_for_sheep_recovery 0
wait # collie
$COLLIE vdi check test
$COLLIE cluster info | _filter_cluster_info

# disk failures after node event
_safe_remove $STORE/1/d0
dd if=/dev/zero | $COLLIE vdi write test &
sleep 1
_kill_sheep 2
sleep 1
_safe_remove $STORE/1/d1
_wait_for_sheep_recovery 0
wait # collie
$COLLIE vdi check test
$COLLIE cluster info | _filter_cluster_info
