#!/bin/bash

# Test master node killing and master transfer

. ./common

for i in 0 1; do
    _start_sheep $i
done

_wait_for_sheep 2

# start Sheepdog with two nodes
_cluster_format

# kill the master node
_kill_sheep 0
_wait_for_sheep 1 1

# start another sheep
_start_sheep 2

# kill all sheeps
nr=2
for i in 1 2; do
    _wait_for_sheep $nr $i
    _kill_sheep $i
    nr=$(($nr - 1))
done

for i in 0 1 2; do
    _start_sheep $i
    nr=$(($nr + 1))
    _wait_for_sheep $nr 0
done

_wait_for_sheep 3
echo check whether all nodes have the same cluster info
for i in 0 1 2; do
    $DOG cluster info -p 700$i | _filter_cluster_info
done
