#!/bin/bash

# Test cluster membership by killing and adding nodes

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 1; do
    _start_sheep $i
done

_wait_for_sheep 2
# start Sheepdog with two nodes
_cluster_format -c 1

for i in 2 3 4; do
    _wait_for_sheep 2 $((i - 2))
    _kill_sheep $((i - 2))
    _wait_for_sheep 1 $((i - 1))

    _start_sheep $i
done

_wait_for_sheep 2 4

$COLLIE cluster shutdown -p 7004
_wait_for_sheep_stop

nr=0
for i in 0 1 2 3 4; do
    _start_sheep $i
    nr=$(($nr + 1))
    _wait_for_sheep $nr 0
done

_wait_for_sheep 5
echo check whether all nodes have the same cluster info
for i in 0 1 2 3 4; do
    $COLLIE cluster info -p 700$i | _filter_cluster_info
done
