#!/bin/bash

# Test data integrity after joining a new node

. ./common

# start three sheep daemons
for i in 0 1 2; do
    _start_sheep $i
done

_wait_for_sheep 3

_cluster_format -c 2

# create a pre-allocated vdi
$DOG vdi create test 80M -P

# stop the 3rd node
_kill_sheep 2

# write data to the vdi
_random | $DOG vdi write test

# restart the 3rd node
_start_sheep 2

_wait_for_sheep_recovery 0

# show md5sum of the vdi on each node
for i in 0 1 2; do
    $DOG vdi read test -p 700$i | md5sum > $STORE/csum.$i
done

diff -u $STORE/csum.0 $STORE/csum.1
diff -u $STORE/csum.0 $STORE/csum.2
