#!/bin/bash

# Test gateway only functionality

. ./common

for i in 0 1 2; do
    _start_sheep $i
done

_wait_for_sheep 3

# add gateway node
_start_sheep 4 "-g"

_wait_for_sheep 4

echo check the number of vnodes
$DOG node list
