#!/bin/bash

# Test snapshot functionality

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 1 2; do
    _start_sheep $i
done

_wait_for_sheep 3

_cluster_format -c 1

$QEMU_IMG create sheepdog:test 4G
for i in `seq 1 9`; do
    $QEMU_IO -c "write 0 512 -P $i" sheepdog:test | _filter_qemu_io
    $QEMU_IMG snapshot -c tag$i sheepdog:test
done

$QEMU_IO -c "read 0 512 -P 9" sheepdog:test | _filter_qemu_io
for i in `seq 1 9`; do
    $QEMU_IO -c "read 0 512 -P $i" sheepdog:test:tag$i | _filter_qemu_io
done
