#!/bin/bash

# Test vdi setattr/getattr

. ./common

for i in 0 2; do
    _start_sheep $i
done

_wait_for_sheep 2

_cluster_format -c 2
$DOG vdi create test 4G

echo -n value > $STORE/tmp.dat

echo "key shouldn't be found"
$DOG vdi getattr test key

$DOG vdi setattr test key value
$DOG vdi getattr test key | diff - $STORE/tmp.dat

$DOG vdi setattr test key value -d

echo "key shouldn't be found"
$DOG vdi getattr test key

status=0
