#!/bin/bash

# Test vdi setattr/getattr

. ./common

for i in `seq 0 5`; do
    _start_sheep $i
done

_wait_for_sheep 6

_cluster_format -c 2
_vdi_create test 4G

echo -n value > $STORE/tmp.dat

echo "key shouldn't be found"
$DOG vdi getattr test key

$DOG vdi setattr test key value
$DOG vdi getattr test key | diff - $STORE/tmp.dat

$DOG vdi setattr test key value -d

echo "key shouldn't be found"
$DOG vdi getattr test key

status=0
