#!/bin/bash

# Test object cache writethrough mode

. ./common

for i in `seq 0 2`; do
    _start_sheep $i "-w size=100"
done

_wait_for_sheep "3"

_cluster_format -c 2

$DOG vdi create test 4M

_random | $DOG vdi write test

for port in `seq 0 2`; do
    $DOG vdi read test -p 700$port | md5sum > $STORE/csum.$port
done

for port in `seq 1 2`; do
    diff -u $STORE/csum.0 $STORE/csum.$port
done
