#!/bin/bash

# Test that writing to a cluster that only has gateways fails

. ./common

for i in `seq 0 2`; do
    _start_sheep $i "-g"
done

_wait_for_sheep "3"

_cluster_format -c 3

echo "creating a VDI should fail without data nodes available"
$DOG vdi create test 100M

status=0
