#!/bin/bash

# Test that writing to a cluster that only has gateways fails

. ./common

for i in `seq 0 5`; do
    _start_sheep $i "-g"
done

_wait_for_sheep 6

_cluster_format -c 3

echo "creating a VDI should fail without data nodes available"
_vdi_create test 100M

status=0
