#!/bin/bash

# Test sheep recovery logic breadth-first algorithm

. ./common

for i in `seq 0 3`; do
    _start_sheep $i
done

_wait_for_sheep "4"

_cluster_format -c 2

$DOG vdi create test0 40M
$DOG vdi create test1 40M

_kill_sheep 3

_wait_for_sheep_recovery 0

find $STORE -name '80fd32fc00000000' | _filter_store | sort
