#!/bin/bash

# Test sheep VDI redundancy level

. ./common

for i in `seq 0 6`; do
	_start_sheep $i;
done

_wait_for_sheep 7

_cluster_format -c 3

for i in `seq 2 4`; do
	$DOG vdi create test$i 20M -c $i -P
done

$DOG vdi snapshot -s tag test2
$DOG vdi clone -s 1 test2 clone -c 3


for i in `seq 2 3`; do
	_kill_sheep $i;
done

for i in `seq 7 8`; do
	_start_sheep $i;
done

_wait_for_sheep_recovery 0

$DOG vdi delete clone
$DOG vdi delete -s 1 test2

_vdi_list

for i in `seq 2 4`; do
	$DOG vdi object test$i -i 1;
done

