#!/bin/bash

# Test cluster snapshot

. ./common
for i in `seq 0 3`; do
	_start_sheep $i;
done
_wait_for_sheep 4

TMPDIR="$STORE/tmp"
rm -rf $TMPDIR

_cluster_format -c 3

$COLLIE vdi create test1 10M
$COLLIE vdi create test2 10M

_random | $COLLIE vdi write test1
_random | $COLLIE vdi write test2
$COLLIE vdi read test1 | md5sum > $STORE/csum.11.org
$COLLIE vdi read test2 | md5sum > $STORE/csum.21.org
$COLLIE vdi snapshot test1
$COLLIE vdi snapshot test2
$COLLIE cluster snapshot save s1 $TMPDIR
$COLLIE cluster snapshot list $TMPDIR | _filter_date

_random | $COLLIE vdi write test1
_random | $COLLIE vdi write test2
$COLLIE vdi read test1 | md5sum > $STORE/csum.12.org
$COLLIE vdi read test2 | md5sum > $STORE/csum.22.org
$COLLIE vdi snapshot test1
$COLLIE vdi snapshot test2
$COLLIE cluster snapshot save s2 $TMPDIR
$COLLIE cluster snapshot list $TMPDIR | _filter_date

$COLLIE vdi list | _filter_short_date

_cleanup
for i in `seq 0 3`; do
	_start_sheep $i;
done
_wait_for_sheep 4

_cluster_format -c 3
$COLLIE cluster snapshot load s1 $TMPDIR
$COLLIE vdi list | _filter_short_date

$COLLIE vdi read test1 | md5sum > $STORE/csum.11.new
$COLLIE vdi read test2 | md5sum > $STORE/csum.21.new
diff -u $STORE/csum.11.org $STORE/csum.11.new
diff -u $STORE/csum.21.org $STORE/csum.21.new

_cleanup
for i in `seq 0 3`; do
	_start_sheep $i;
done
_wait_for_sheep 4

$COLLIE cluster snapshot load s2 $TMPDIR
$COLLIE vdi list | _filter_short_date

_cleanup
for i in `seq 0 3`; do
	_start_sheep $i;
done
_wait_for_sheep 4

$COLLIE cluster snapshot load 2 $TMPDIR
$COLLIE vdi list | _filter_short_date

$COLLIE vdi read -s 2 test1 | md5sum > $STORE/csum.12.new
$COLLIE vdi read -s 2 test2 | md5sum > $STORE/csum.22.new
diff -u $STORE/csum.12.org $STORE/csum.12.new
diff -u $STORE/csum.22.org $STORE/csum.22.new

$COLLIE vdi read test1 | md5sum > $STORE/csum.12.new
$COLLIE vdi read test2 | md5sum > $STORE/csum.22.new
diff -u $STORE/csum.12.org $STORE/csum.12.new
diff -u $STORE/csum.22.org $STORE/csum.22.new

$COLLIE vdi read -s 1 test1 | md5sum > $STORE/csum.11.new
$COLLIE vdi read -s 1 test2 | md5sum > $STORE/csum.21.new
diff -u $STORE/csum.11.org $STORE/csum.11.new
diff -u $STORE/csum.21.org $STORE/csum.21.new
