#!/bin/bash

# Test vdi list after cluster restart

. ./common

_start_sheep 0
_wait_for_sheep 1

_cluster_format -c 1

for i in 1 2 3; do
    $COLLIE vdi create test$i ${i}00MB
done

_vdi_list

$COLLIE cluster shutdown
_wait_for_sheep_stop

_start_sheep 0
_wait_for_sheep 1

_vdi_list
