#!/bin/bash

# Test vdi list after cluster restart

. ./common

_start_sheep 0
_wait_for_sheep 1

_cluster_format -c 1

for i in 1 2 3; do
    $COLLIE vdi create test$i ${i}00MB
done

$COLLIE vdi list | _filter_short_date

$COLLIE cluster shutdown
_wait_for_sheep_stop

_start_sheep 0
_wait_for_sheep 1

$COLLIE vdi list | _filter_short_date
