#!/bin/bash

# Test format cluster during node membership changes

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in `seq 0 7`; do
    _start_sheep $i
done

while true; do
    $COLLIE cluster format 2> /dev/null
    if [ $? == 0 ]; then
        break
    fi
    # try again until at least one sheep starts up
done &
pid=$!

for i in `seq 4 7`; do
    _kill_sheep $i
done

# wait for collie to finish
for cnt in `seq 60`; do # wait at most 60 seconds
    jobs 1 > /dev/null 2>&1
    if [ $? != 0 ]; then
	break
    fi
    sleep 1
done
kill $pid > /dev/null 2>&1

for i in `seq 4 7`; do
    _start_sheep $i
done

_wait_for_sheep "8"

for i in `seq 0 7`; do
    $COLLIE cluster info -p 700$i | head -1
    $COLLIE node list -p 700$i
done
