#!/bin/bash

# Test vdi deletion

. ./common

for i in 0 1 2; do
    _start_sheep $i
done

_wait_for_sheep 3

_cluster_format -c 2

echo "delete snapshot image before current one"
$DOG vdi create test 4G
$DOG vdi snapshot test -s snap
_vdi_list

$DOG vdi delete test -s snap
$DOG vdi delete test -s snap # error
_vdi_list

$DOG vdi delete test
$DOG vdi delete test # error
_vdi_list

echo "delete current image before snapshot one"
$DOG vdi create test 4G
$DOG vdi snapshot test -s snap
_vdi_list

$DOG vdi delete test
$DOG vdi delete test # error
_vdi_list

$DOG vdi delete test -s snap
$DOG vdi delete test -s snap # error
_vdi_list
