#!/bin/bash

# Test journal file replay

. ./common

_start_sheep 0 "-j size=64"

_wait_for_sheep 1

_cluster_format -c 1

$DOG vdi create test 4G

# write something to vdi 'test'
echo "hello" | $DOG vdi write test 0 512
echo "sheepdog" | $DOG vdi write test 4M 512
# corrupt the vdi...
_kill_sheep 0
if $MD; then
	rm $STORE/0/d*/807c2b2500000000
	rm $STORE/0/d*/007c2b25*
else
	rm $STORE/0/obj/807c2b2500000000
	rm $STORE/0/obj/007c2b25*
fi

# do the journal replay
_start_sheep 0 "-j size=64"
_wait_for_sheep 1

sleep 3

_vdi_list
$DOG vdi read test 0 512 | tr -d [:cntrl:]
echo -n ' '
$DOG vdi read test 4M 512 | tr -d [:cntrl:]
echo ''
