#!/bin/bash

# Test cluster with too few living nodes

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 1; do
    _start_sheep $i
done
_wait_for_sheep 2
_cluster_format
$COLLIE cluster info | _filter_cluster_info

_start_sheep 2
_wait_for_sheep 3
$COLLIE cluster info | _filter_cluster_info

_kill_sheep 2
_wait_for_sheep 2
$COLLIE cluster info | _filter_cluster_info
