#!/bin/bash

# Test cluster with too few living nodes

. ./common

for i in 0 1; do
    _start_sheep $i
done
_wait_for_sheep 2
_cluster_format
$DOG cluster info | _filter_cluster_info

_start_sheep 2
_wait_for_sheep 3
$DOG cluster info | _filter_cluster_info

_kill_sheep 2
_wait_for_sheep 2
$DOG cluster info | _filter_cluster_info
