#!/bin/bash

# Test force cluster recovery with new nodes

. ./common

for i in 0 1 2 3; do
    _start_sheep $i
done
_wait_for_sheep 4
_cluster_format
$COLLIE vdi create test 20M -P
$COLLIE cluster info | _filter_cluster_info

$COLLIE cluster shutdown
_wait_for_sheep_stop

for i in 0 1 2 4; do
    _start_sheep $i
done
_wait_for_sheep 4
for i in 0 1 2 4; do
    $COLLIE cluster info -p 700$i | _filter_cluster_info
    $COLLIE vdi list | _filter_short_date
done

echo yes | $COLLIE cluster recover force
echo ""

_wait_for_sheep_recovery 0
$COLLIE vdi check test | sort

for i in 0 1 2 4; do
    $COLLIE cluster info -p 700$i | _filter_cluster_info
    $COLLIE vdi list | _filter_short_date
done

_start_sheep 3
_wait_for_sheep 5
for i in 0 1 2 3 4; do
    $COLLIE cluster info -p 700$i | _filter_cluster_info
    $COLLIE vdi list | _filter_short_date
done
