#!/bin/bash

# Test stale objects purging with different disk size.
. ./common

_need_to_be_root

_make_device 0 $((1024 ** 3))
_make_device 1 $((2 * 1024 ** 3))
_make_device 2 $((3 * 1024 ** 3))
_make_device 3 $((3 * 1024 ** 3))

#start three in different size
for i in 0 1 2; do
	_start_sheep $i
done
_wait_for_sheep 3
_cluster_format

$DOG vdi create test 100M -P
$DOG cluster info | _filter_cluster_info

#start recovery
_start_sheep 3

_wait_for_sheep 4
_wait_for_sheep_recovery 0
$DOG cluster info | _filter_cluster_info

#test no object in .stale
ls $STORE/*/*/.stale | grep ^- | wc -l
