#!/bin/bash

# Test discard/trim
seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 1 2; do
	_start_sheep $i "-w size=200"
done
_wait_for_sheep 3
_cluster_format
$COLLIE vdi create test 100M
dd if=/dev/zero | $COLLIE vdi write -w test
qemu-io -c "discard 0 100m" sheepdog:test | _filter_qemu_io
$COLLIE vdi check test
for i in `seq 0 24`; do
	$COLLIE vdi object test -i $i;
done
_node_info
