#!/bin/bash

# Test live snapshot

. ./common

for i in `seq 0 2`; do
    _start_sheep $i
done

_wait_for_sheep 3

_cluster_format -c 3
$DOG vdi create test 4M

_input()
{
    for i in `seq 1 10`; do
	echo "multiwrite -P $i 0 1k ; 2k 1k ; 4k 1k ; 8k 1k"
	sleep 1
	$DOG vdi snapshot test -s snap$i
    done

    echo quit
}

_input | $QEMU_IO sheepdog:test > /dev/null

_vdi_list
$DOG vdi tree | _filter_short_date

for i in `seq 1 10`; do
    $DOG vdi read test -s snap$i | md5sum
done
