#!/bin/bash

# Test unaligned dog vdi read/write

. ./common

for i in `seq 0 2`; do
    _start_sheep $i
done

_wait_for_sheep 3

_cluster_format

$DOG vdi create test 1234
sleep 1
$DOG vdi list -r test | awk '{$7="MASKED";print $0}'

echo hello | $DOG vdi write test 1 6
$DOG vdi read test 1 6
echo world | $DOG vdi write test 1 6
$DOG vdi read test 1 6

echo h*** | $DOG vdi write test 510 512
echo h!!! | $DOG vdi write test 510 512
$DOG vdi read test 510 5
echo ^^ | $DOG vdi write test 511 2
$DOG vdi read test 510 5
echo xxx | $DOG vdi write test 1020 4
$DOG vdi read test 1020 4
$DOG vdi read test 510 5
$DOG vdi read test 1 6
