#!/bin/bash

# Test join to the clean cluster

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1        # failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_cleanup

for i in 0 1 2; do
    _start_sheep $i
done

_wait_for_sheep 3

# start Sheepdog with 3 nodes
_cluster_format

$COLLIE cluster shutdown -p 7000
_wait_for_sheep_stop

for i in 3 4 5; do
    _start_sheep $i
done

_wait_for_sheep 3 3

for i in 0 1 2; do
    _start_sheep $i
done

_wait_for_sheep 6

for i in `seq 0 5`; do
    $COLLIE cluster info -p 700$i | _filter_cluster_info
done
