#!/bin/bash

# Test cluster format option

. ./common

for i in `seq 0 6`; do
    _start_sheep $i
done

_wait_for_sheep 7

_cluster_format -c 4:2

$DOG vdi create test1 20M
$DOG vdi create -c 2 test2 20M
$DOG vdi create -c 2:1 test3 20M
_vdi_list
$DOG cluster shutdown
_wait_for_sheep_stop

for i in `seq 0 6`; do
    _start_sheep $i
done
_wait_for_sheep 7
$DOG vdi create test4 20M
_vdi_list
