#!/bin/bash

# Test fast deepcopy snapshot can produce a same result with ordinal deepcopy snapshot

. ./common

for i in 0 1 2; do
    _start_sheep $i
done
_wait_for_sheep 3
_cluster_format -c 2

$DOG vdi create test 128M -P
$DOG vdi snapshot test --no-share

_node_info
_vdi_list

$DOG vdi delete test
$DOG vdi delete test -s 1

$DOG vdi create test 128M -P
$DOG vdi snapshot test --no-share --fast-deep-copy

_node_info
_vdi_list
