#!bash

_dog_cluster_format()
{
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"

    case "$cur" in
        -*)
            COMPREPLY=(${COMPREPLY[@]} \
                $( compgen \
                -W "-c --copies" \
                -- ${cur} ))
            ;;
    esac
}

_dog_cluster_recover()
{
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"

    case "$cur" in
        -*)
            COMPREPLY=(${COMPREPLY[@]} \
                $( compgen \
                -W "-f --force" \
                -- ${cur} ))
            ;;
    esac
}

_dog_vdi_create()
{
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"

    case "$cur" in
        -*)
            COMPREPLY=(${COMPREPLY[@]} \
                $( compgen \
                -W "-P --prealloc" \
                -- ${cur} ))
            ;;
    esac
}

_dog_vdi_snapshot()
{
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"

    case "$cur" in
        -*)
            COMPREPLY=(${COMPREPLY[@]} \
                $( compgen \
                -W "-s --snapshot" \
                -- ${cur} ))
            ;;
    esac
}

_dog_vdi_clone()
{
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"

    case "$cur" in
        -*)
            COMPREPLY=(${COMPREPLY[@]} \
                $( compgen \
                -W "-P --prealloc -s --snapshot" \
                -- ${cur} ))
            ;;
    esac
}

_dog_vdi_read()
{
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"

    case "$cur" in
        -*)
            COMPREPLY=(${COMPREPLY[@]} \
                $( compgen \
                -W "-s --snapshot" \
                -- ${cur} ))
            ;;
    esac
}

_dog_vdi_delete()
{
    local cur dog vdilist
    cur="${COMP_WORDS[COMP_CWORD]}"
    dog="${COMP_WORDS[0]}"
    vdilist="$(${dog} vdi list | tail -n+3 | grep '^  ' | awk '{print $1}')"

    case "$cur" in
        -*)
            COMPREPLY=(${COMPREPLY[@]} \
                $( compgen \
                -W "-s --snapshot" \
                -- ${cur} ))
            ;;
        *)
            COMPREPLY=($( compgen -W "${vdilist}" -- ${cur} ))
            ;;
    esac
}

_dog_vdi_object()
{
    local cur dog vdilist
    cur="${COMP_WORDS[COMP_CWORD]}"
    dog="${COMP_WORDS[0]}"
    vdilist="$(${dog} vdi list | tail -n+3 | grep '^  ' | awk '{print $1}')"

    case "$cur" in
        -*)
            COMPREPLY=(${COMPREPLY[@]} \
                $( compgen \
                -W "-i --index -s --snapshot" \
                -- ${cur} ))
            ;;
        *)
            COMPREPLY=($( compgen -W "${vdilist}" -- ${cur} ))
            ;;
    esac
}

_dog_vdi_setattr()
{
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"

    case "$cur" in
        -*)
            COMPREPLY=(${COMPREPLY[@]} \
                $( compgen \
                -W "-d --delete -x --exclusive" \
                -- ${cur} ))
            ;;
    esac
}

_dog_cluster()
{
    local opts
    opts="info format shutdown recover snapshot"

    case "$1" in
        info)
            ;;
        format)
            _dog_cluster_format
            ;;
        shutdown)
            ;;
        recover)
            _dog_cluster_recover
            ;;
        snapshot)
            ;;
        "")
            COMPREPLY=($( compgen \
                -W "${opts}" \
                -- "${COMP_WORDS[COMP_CWORD]}" ))
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

_dog_node()
{
    local opts
    opts="info list recovery kill cache"

    case "$1" in
        info)
            ;;
        list)
            ;;
        recovery)
            ;;
        kill)
            ;;
        cache)
            ;;
        "")
            COMPREPLY=($( compgen \
                -W "${opts}" \
                -- "${COMP_WORDS[COMP_CWORD]}" ))
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

_dog_vdi()
{
    local opts
    opts="create snapshot clone resize read write \
list tree graph delete object setattr getattr track check \
rollback flush backup restore"

    case "$1" in
	create)
	    _dog_vdi_create
	    ;;
	snapshot)
	    _dog_vdi_snapshot
	    ;;
	clone)
	    _dog_vdi_clone
	    ;;
	resize)
	    ;;
	read)
	    _dog_vdi_read
	    ;;
	write)
	    ;;
        list)
            ;;
        tree)
            ;;
        graph)
            ;;
        delete)
            _dog_vdi_delete
            ;;
        object)
            _dog_vdi_object
            ;;
        setattr)
            _dog_vdi_setattr
            ;;
        getattr)
            ;;
        track)
            ;;
        check)
            ;;
	rollback)
	    ;;
	flush)
	    ;;
	backup)
	    ;;
	restore)
	    ;;
        "")
            COMPREPLY=($( compgen \
                -W "${opts}" \
                -- "${COMP_WORDS[COMP_CWORD]}" ))
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

_dog()
{
    local opts cur cmd subcmd i
    opts="cluster node vdi"
    cur="${COMP_WORDS[COMP_CWORD]}"

    if [ $COMP_CWORD -gt 1 ]; then
        cmd=${COMP_WORDS[1]}
    fi

    if [ $COMP_CWORD -gt 2 ]; then
        subcmd=${COMP_WORDS[2]}
    fi

    COMPREPLY=($( compgen -W "-a --address -p --port -h --help" -- ${cur} ))

    case "${cmd}" in
        cluster)
            _dog_cluster ${subcmd}
            ;;
        node)
            _dog_node ${subcmd}
            ;;
        vdi)
            _dog_vdi ${subcmd}
            ;;
        "")
            COMPREPLY=($( compgen -W "${opts}" -- ${cur} ))
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _dog dog
