#!/usr/bin/perl

# Examples
#
# run-dogs.pl -n=5 -d=/tmp/1203

$sport = 9000;
$dport = 7000;
$mport = 45566;
$nr = 1;
@hosts = ();
$home = ".";

$dir = "/tmp/".rand(100);

while (@ARGV && $ARGV[0] =~ m/^-/) {
    $_ = shift(@ARGV);

    if (m/^-n=([0-9]*)$/) {
	$nr = $1;
    } elsif (m/^-d=(.*)$/) {
	$dir = $1;
    } elsif (m/^-m=(.*)$/) {
	$mport = $1;
    } elsif (m/^-h=(.*)$/) {
	@hosts = &expand(split ':', $1);
    } elsif (m/^-H=(.*)$/) {
	$home = $1;
    }
}

print("killing all dogs and sheeps...\n\n");
system("$home/script/stop-sheepdog [0-100]");

foreach $pidfile (`ls /tmp/sheepdog*.pid`) {
    chomp $pidfile;
    system "jsvc -stop -pidfile $pidfile net.osrg.sheepdog.Sheepdog";
}

my %count;

foreach $host (grep {!$count{$_}++} @hosts) {
    system("$home/script/stop-sheepdog [0-100]");
}

for ($i = 0; $i < $nr; $i++, $sport++, $dport++) {
    $_dir = $dir.$i;
    if ($hosts[$i]) {
	print("ssh $hosts[$i] $home/sheep/sheep --dport $dport --sport $sport $_dir -d\n");
	system("ssh $hosts[$i] $home/sheep/sheep --dport $dport --sport $sport $_dir -d");
	print("ssh $hosts[$i] $home/dog/dog --mport $mport --dport $dport --sport $sport -d\n");
	system("ssh $hosts[$i] $home/dog/dog --mport $mport --dport $dport --sport $sport -d");
    } else {
	print("$home/sheep/sheep --dport $dport --sport $sport $_dir -d\n");
	system("$home/sheep/sheep --dport $dport --sport $sport $_dir -d");
	print("$home/dog/dog --mport $mport --dport $dport --sport $sport -d\n");
	system("$home/dog/dog --mport $mport --dport $dport --sport $sport -d");
    }
}

sub expand {
    my @hosts = @_;
    my @ret = ();
    for my $host (@hosts) {
	if ($host =~ /\[(\d+)-(\d+)\]/) {
	    push @ret, &expand(map { $` . $_ . $' } ($1..$2));
	} else {
	    push @ret, $host;
	}
    }
    return @ret;
}

