#!/bin/bash
set -xueo pipefail
export LANG=C LC_ALL=C

set_up() {
  sudo rm -rf /tmp/sheepdog
  sudo rm -rf /tmp/sheepdog_locks
  sudo rm -f /tmp/sheepdog_shm
}

exec_functional() {
  sudo ./tests/functional/check
}

#main
set_up
exec_functional
